### ISSUE TITLE
Add heart multipliers to plurality score calculation

### ISSUE THREAD

**Issue by MartinBenediktBusch** [lexicongovernance/pluraltools-backend#263]
### Overview 

In our baseline setup each participant is endowed with a fixed number of hearts to distribute between options where 1 heart equals 1 vote. However, users vote power should differ by academic credential. That is, the vote of users with a higher academic credential should count more than the vote of users with a lower academic credentail. 

### Solution 

Implement a multiplier conditonal on a given academic credential. For example, consider that we give holders of a PhD a multiplier of `1.5` which means that 1 heart is worth `1.5` votes. 

### Required table changes

- create `usersToCredentials` table that has a `user_id`, `credential_id`, and `multiplier` column. We could use this table to edit multipliers by user. For example, created credentials we assign a default multiplier of 1.  

### Required service changes 

- implement user to credentials service that populates the `userToCredentials` table.
- apply multiplier for votes by `user` and `option_id` before calculating the plurality score.

**Comment by diegoalzate** [comment]
learning from out groups mistakes we might want to make this a bit more dynamic.

### proposed solution
Vey similar to groups but they will be called multipliers

- multiplierCategories: will allow us to have multiple levels of multipliers in case we want more fields e.g music taste
- multipliers: holds the multiplier label and vaue
- users to multipliers: can include multiplierCategoryID and multiplierID
- users: existing table
