### ISSUE TITLE
stop making registrations turn to DRAFT

### ISSUE THREAD

**Issue by diegoalzate** [lexicongovernance/pluraltools-backend#392]
## overview
on update registrations turn automatically to DRAFT, do not update this field

### expected behaviour
format: old -> new

DRAFT -> DRAFT
APPROVED -> APPROVED

**Comment by MartinBenediktBusch** [comment]
Also should not kick me out if I play with the link (happend in the test):

![Screenshot 2024-05-16 191645](https://github.com/lexicongovernance/pluraltools-backend/assets/43137759/e05a39f8-71af-4a1e-86f4-c8a4ee56b58b)
